# Site settings
title: BYFC
subtitle: Tournament 2022
email: tournament.committee@barmingyouth.co.uk
description: Welcome to the Barming Youth FC tournament 2022. See below for useful information; use the menu (top right) to view results<br />£35 per team<br /><br />&bull;Sat am&mdash;Under 7, Under 8, Under 9, Under, 10<br />&bull;Sat pm&mdash;Under 11, Under 12, Under 13, Under 14<br />&bull;Sun am&mdash;Under 15, Under 18, Men, Vets<br />&bull;Sun pm&mdash;Under 12 girls, Under 13 girls, Ladies 16+.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 55 Beverley Road
city: Maidstone
state: Kent
zip_code: ME16 9DU
country: 
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/BYFCTournament
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/BarmingYouthFC

# Build settings
markdown: kramdown

sass:
  style: compressed
