# Site settings
title: BYFC
subtitle: Tournament 2018
email: webmaster@barmingyouth.co.uk
description: Welcome to the Barming Youth FC tournament 2018. See below for useful information; use the menu (top right) to view results.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 55 Beverley Road
city: Maidstone
state: Kent
zip_code: ME16 9DU
country: 
phone: 07952 267596

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/BYFCTournament
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/BarmingYouthFC

# Build settings
markdown: kramdown

sass:
  style: compressed
