# Site settings
title: BYFC
subtitle: Tournament 2023
email: tournament.committee@barmingyouth.co.uk
description: Welcome to the Barming Youth FC tournament 2023.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city: Maidstone
state: Kent
zip_code:
country:
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 0

# Social settings
500px_url:
facebook_url: https://www.facebook.com/BYFCTournament
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/BarmingYouthFC

# Build settings
markdown: kramdown

sass:
  style: compressed
